# Generated by Django 4.1.3 on 2022-11-11 17:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('descript', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('chapter', models.IntegerField()),
                ('season', models.IntegerField()),
                ('rating', models.FloatField()),
                ('director', models.CharField(max_length=40)),
                ('actor', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('studio', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
                'unique_together': {('name', 'studio')},
            },
        ),
    ]
