# Generated by Django 4.1.3 on 2022-11-25 05:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('studio', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie')),
                ('rating', models.FloatField()),
            ],
            options={
                'unique_together': {('name', 'studio')},
            },
        ),
    ]
